# Generated by Django 5.0.4 on 2024-08-23 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni_app', '0008_transcript'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transcript',
        ),
    ]
